### ISSUE TITLE
More Features for this great flag-counter !

### ISSUE THREAD

**Issue by sigih** [sgiehl/piwik-plugin-FlagCounter#1]
Hello !
I use the very easy to use flag counter ... on my website.

But ... it would be great if there will be more features in the future like:
* change text color
* change text size
* max. number s of points - like max. 999, 99999, 9999999 - Anzahl der max. Stellen - from 3 to 9 will be great
* position between the flags - Abstand zw. Flaggen und Text / Flagge
* center, left, right orientated
* page distances - Seitenabstände

.. thats all for the first time ... next time more

TNX
Siegfried
www.juror.at

**Comment by sgiehl** [comment]
Thanks for your feedback. I'm not sure when I've some time to implement some new features. But I'll do my best ;)

**Comment by sgiehl** [comment]
I'm closing this issue now as I've splitted your requests into several issues.
