### ISSUE TITLE
make flag sorted (ascending and descending)

### ISSUE THREAD

**Issue by sigih** [sgiehl/piwik-plugin-FlagCounter#8]
Hello Stefan,

I use PIWIK 2.13.b1 and found that the flag are not sorted correct.
Can you implement a function to sort it ascending  and/or descending.

see Screenshots - made it few minutes ago from one of my websites.

best regards
Siegfried - sigih.

![sigi-0008](https://cloud.githubusercontent.com/assets/10097597/6997476/dee9bd0a-dbbc-11e4-8854-066ebad61714.png)
![sigi-0009](https://cloud.githubusercontent.com/assets/10097597/6997475/dee8d354-dbbc-11e4-8b37-31d69b6c0bad.png)

**Comment by sgiehl** [comment]
Thx for the suggestions. That should already be fixed with f7cb57ff and will be included in the next release
