### ISSUE TITLE
Flagcounter only shows data of today

### ISSUE THREAD

**Issue by Human2000** [sgiehl/piwik-plugin-FlagCounter#9]
Hi,

i use the following link,
index.php?module=FlagCounter&action=image&idSite=2&period=range&date=2014-03-18,today&cols=2&rows=6

But i only see data from today. Is it possible that it have no data before the activation date of the plugin ?

**Comment by Human2000** [comment]
OK, solved it myself. its the  cache time. i set it down to 1 second. so it refreshed immediately.

**Comment by sgiehl** [comment]
Well, that is a bug, indeed. The cache should be set based on the period and date

**Comment by sgiehl** [comment]
Should be fixed. I'll release a new minor version now
